# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  selector:
    matchLabels:
      app: todo-app
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: todo_app:prod
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: MONGO_DATABASE_NAME
          value: "todo_db"
        - name: LOGIN_DISABLED
          value: "FALSE"
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: github-client
              key: backend-GITHUB_CLIENT_ID
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: todo-secrets
              key: backend-GITHUB_CLIENT_SECRET
        - name: MONGO_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: mongo-connection
              key: backend-MONGO_CONNECTION_STRING
        - name: LOGGLY_TOKEN
          valueFrom:
            secretKeyRef:
              name: loggly
              key: backend-LOGGLY_TOKEN
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret-key
              key: backend-SECRET_KEY

