version: '3'

services:
  dev:
    build:
      context: .
      target: development
    volumes:
      - type: bind
        source: \Users\craig\Apprenticeship\DevOps-Course-Starter\todo_app
        target: /app/todo_app todo_app:dev
    ports: 
      - 5000:5000
    env_file: .env
  
  prod:
    build:
      context: .
      target: production
    ports: 
      - 8000:8000
    env_file: .env