- name: my playbook
  hosts: webservers
  remote_user: ec2-user

  tasks:
    - name: Install python3
      yum:
        name: python3
        state: latest
      become: yes

    - name: Install Git
      yum:
        name: git
        state: latest
      become: yes

    - name: Use curl to Install poetry
      ansible.builtin.shell: curl -sSL https://install.python-poetry.org | python3 -
      args:
        creates: /home/ec2-user/.local/bin/poetry

    - name: Run command if /opt/todoapp does not exist 
      ansible.builtin.file:
        path: /opt/todoapp
        state: directory
        mode: '0777'
      become: yes

    - name: Git checkout
      ansible.builtin.git:
        repo: https://github.com/CraigAAAAAAAAAAA/DevOps-Course-Starter.git
        dest: /opt/todoapp
        version: exercise-4 
