name: Continuous Integration 
on:
  push:
    paths-ignore:
      - README.md
  pull_request:
    paths-ignore:
      - README.md 
  schedule:
    - cron: "0 23 * * *"

jobs:
  build:
    name: Build and test 
    runs-on: ubuntu-latest
    
    steps: 
    - uses: actions/checkout@v2 
    - name: build test docker image
      run: docker build --target test --tag todo_app:test .

    - name: run docker integration test container
      run: docker run --env-file .env.test todo_app:test todo_app/tests/test_app.py
      
    - name: run docker unit test container
      run: docker run --env-file .env.test todo_app:test todo_app/tests/test_unit.py

    - name: run docker E2E test container
      run: docker run -e TRELLO_API_KEY=${{secrets.TRELLO_API_KEY}} -e TRELLO_API_TOKEN=${{secrets.TRELLO_API_TOKEN}} -e SECRET_KEY=anything todo_app:test todo_app/tests/test_e2e.py
    
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    
    - name: Run Snyk to check static code
      uses: snyk/actions/python@master
      env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
          command: code test
    
  production:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/Module-8'

    steps: 
    - name: checkout
      uses: actions/checkout@v2

    - uses: satackey/action-docker-layer-caching@v0.0.11
    
    - name: docker login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: build production image
      run: docker build --target production --tag craigbeasley/todo_app:prod .
    
    - name: push docker image
      run: docker push craigbeasley/todo_app:prod

    - name: Build, Push and Release a Docker container to Heroku
      uses: gonuit/heroku-docker-deploy@v1.3.3
      with:
        email: ${{ secrets.HEROKU_EMAIL }}
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        dockerfile_directory: ./
        dockerfile_name: Dockerfile
        process_type: web