name: Continuous Integration 
on:
  push:
    paths-ignore:
      - README.md
  pull_request:
    paths-ignore:
      - README.md 
  schedule:
    - cron: "0 23 * * *"

jobs:
  build:
    name: Build and test 
    runs-on: ubuntu-latest
    
    steps: 
    - uses: actions/checkout@v2 
    - name: build test docker image
      run: docker build --target test --tag todo_app:test .

    - name: run docker integration test container
      run: docker run --env-file .env.test todo_app:test todo_app/tests/test_app.py
      
    - name: run docker unit test container
      run: docker run --env-file .env.test todo_app:test todo_app/tests/test_unit.py

    - name: run docker E2E test container
      run: docker run -e MONGO_CONNECTION_STRING=${{secrets.MONGO_CONNECTION_STRING}} -e TEST_MONGO_DATABASE_NAME=${{secrets.TEST_MONGO_DATABASE_NAME}} -e SECRET_KEY=anything todo_app:test todo_app/tests/test_e2e.py
    
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    
    - name: Run Snyk to check static code
      uses: snyk/actions/python@master
      env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
          command: code test
    
  production:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps: 
    - name: checkout
      uses: actions/checkout@v2

    - uses: satackey/action-docker-layer-caching@v0.0.11
           
    - name: docker login
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: build production image
      run: docker build --target production --tag craigbeasley/todo_app:prod .
    
    - name: push docker image
      run: docker push craigbeasley/todo_app:prod

    - name: update Azure 
      run: curl -dH --fail -X POST ${{secrets.AZURE_WEB_HOOK}} 
