name: Continuous Integration 
on:
  schedule:
    - cron: '45 12 * * 1,3'
  push:
    paths-ignore:
      - README.md
  pull_request:
    paths-ignore:
      - README.md 

jobs:
  build:
    name: Build and test 
    runs-on: ubuntu-latest
    
    steps: 
    - uses: actions/checkout@v2 
    - name: build test docker image
      run: docker build --target test --tag todo_app:test .

    - name: run docker test container
      run: docker run --env-file .env.test todo_app:test
    
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    
    - name: Run Snyk to check static code
      uses: snyk/actions/python@master
      env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
          command: code test
          
 

